Manishearth/ChatExchange

chatexchange/rooms.py
This parameter should be used in case you don't want the length check. For
multiline messages, it's sometimes valid to have a message longer than 500
characters, but then CE wouldn't post it anyway. So I added this parameter,
which we need for SmokeDetector's new !!/errorlogs command.
=> Add length_check parameter to send_message method

chatexchange/events.py
Based on [Tim Stone's message](http://chat.stackexchange.com/transcript/message/20305029#20305029):
> That's an invalid assumption about room_id anyway isn't it? I don't think that's provided for at least event_type = 14 (global notifications)
Fixes #84.
=> Don't set room for event when room id isn't passed

chatexchange/browser.py, chatexchange/client.py
When using ChatExchange, it's very useful to know when the chat web socket
is closed; if people can get notified about it, they can re-join the room
to fix everything, but before this commit, it was not possible to find out
when a web socket was closed (except using an except hook, but that's a
bit overkill for one kind of error like this).
=> Add on_websocket_closed as notification

chatexchange/browser.py
If there's no method added to handle a closed websocket, ChatExchange would remain silent about it, but that should not happen.
=> Re-raise exception if on_websocket_closed is None

chatexchange/browser.py
Anywhere else in the Browser class, the room ID as parameter is converted to a string, except here. This is the most likely cause for some errors like http://chat.stackexchange.com/transcript/message/21751188#21751188
=> Convert room ID to string at watch_room_*

chatexchange/browser.py, chatexchange/users.py, test/test_users.py
I've seen some cases where it would be useful to check if a user has >= 20
reputation.
=> Add reputation to User class

README.md
There is a version incompatibility between the pip installed on Ubuntu/available in its official repositories and the latest requests module. As soon as requests is upgraded, pip will stop working. Therefore it is important to upgrade pip too.
=> Problem with pip & requests on Ubuntu

chatexchange/browser.py, chatexchange/rooms.py
Room.get_pingable_user_ids: gets the pingable user IDs
Room.get_pingable_user_names: gets the pingable user names
The methods don't fetch actual User object, because for crowded rooms that
might send lots of web requests.
Important note: to use these methods, logging in on the Client is
required. You'll get an empty response if you don't.
=> Add methods to get pingable user IDs/names

chatexchange/client.py
I noticed that response handling wasn't handled correctly: for example,
throttling wasn't taken in account. I found the causes:
if isinstance(response, str):
and:
if isinstance(response, dict):
These cases would never be true, because response would always be a
Response object.
This commit unpacks the actual value from the Response object so
everything is handled correctly.
=> Fix response handling

chatexchange/client.py
... and when getting rate-limited, add only 1 second to the waiting time.
I've tried this and my bot had no problems when posting 20 messages to
chat.
=> Get rid of BACKOFF_MULTIPLIER

chatexchange/browser.py
To avoid this warning:
```
C:\Python27\lib\site-packages\bs4\__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
To get rid of this warning, change this:
BeautifulSoup([your markup])
to this:
BeautifulSoup([your markup], "html.parser")
```
=> Specify "html.parser" for BeautifulSoup

chatexchange/events.py
Bots using CE now crash when someone stars a message because the user ID
is no longer provided:
http://meta.stackexchange.com/a/264580/229438
=> MessageEvent: set user to None if not passed

chatexchange/browser.py
Stack Exchange has apparently added another `script` element to the
header of the chat page, so when `Browser.get_current_user_ids_in_room()`
searches for the fourth `script` element which contains the list of
users present, it find a `script` in the `head`, not the one it's supposed
to find in the body of the page. This commit fixes that by having it
search for the first `script` in the `body`, which should be more resilient
against future changes in the scripts used in the header. The same
fix is applied to `Browser.get_current_user_names_in_room()`.
=> Fix the BS4 search for the script needed to count current user IDs

chatexchange/browser.py
The same as the last: If the protocol is included in the link, there will be an error
=> Fix login bug

.gitignore, .gitlab-ci.yml, chatexchange/browser.py, examples/chat.py, examples/web_viewer.py, tests/test_client.py, tests/test_events.py, tests/test_messages.py, tests/test_openid_login.py, tests/test_rooms.py, tests/test_users.py
Many live tests were broken because they attempted to use Stack Exchange chat
room 14219 "Chatcoal Chatbox Sandbox", but that room has been repeatedly frozen
due to long periods of inactivity. I updated the tests and moved some messages
so that room 1 "Sandbox" is used instead.
I added a `.gitlab-ci.yaml` configuration file to enable running running tests
on GitLab CI. For live tests, any developers using GitLab can specify their
values for `ChatExchangeU` and `ChatExchangeP` in their project's
`/settings/ci_cd`'s *Secret Variables*. The tests are run against the latest
version of Python 2 and the latest version of Python 3 (not as many different
versions as we've been running on Travis). We put the tests in different
`stages` to force them to them run consecutively, because if they're …
=> Fixes broken tests and adds support for GitLab CI

.gitignore, .gitlab-ci.yml, chatexchange/browser.py, examples/chat.py, examples/web_viewer.py, tests/test_client.py, tests/test_events.py, tests/test_messages.py, tests/test_openid_login.py, tests/test_rooms.py, tests/test_users.py
*depends on #139*
Builds our Epydocs for every commit on GitLab CI, and publishes to the project's GitLab Pages for every new commit on `master` (or `gl-pages`, intended for development).
As an example [here's the latest build output for my GitLab fork](http://banks.gitlab.io/ChatExchange/epydocs/class-tree.html).
=> Build Epydocs to GitLab Pages

.travis.yml, chatexchange/browser.py, chatexchange/events.py, chatexchange/rooms.py, repl, setup.py
- Add `Room.get_current_users()` and `.get_pingable_users()` returning lists of `User` objects. These are intended to replace the current `.get_pingable_user_ids()`, `.get_pingable_user_names()`, `.get_current_user_ids`, `.get_current_user_names()` methods. (We have the information for the `User` object in either case, but existing methods required multiple requests to the server if you wanted the IDs and the user names.)
- Minor changes to event types: renamed one to fix a typo, renamed two others to match the internal names (with backwards-compatibility aliases for all renames), and added placeholder `InternalEventN` events for all unknown-but-valid event IDs. (Some of these can occur for developer users, and without an event class to map on to they could cause a crash.) Added new …
=> Minor improvements

chatexchange/browser.py, chatexchange/users.py, tests/test_users.py
This change adds the `last_message` time to the `User` object. 
This time is found directly above the existing `last_seen` value.
---
---
=> Adds `last_message` time from profile

chatexchange/browser.py
When I originally submitted a PR back in November, I used -2 instead of 2 as the index for the user ID in the link because that would work whether or not the protocol were included in the URL. It seems that SE has changed something because now the username is no longer included, so this line is trying to convert 'users' to an integer. This fix doesn't try to hardcode the position of the ID, but instead gets it by finding the position of 'users' in the URL and then using the next one. There might be a better way of doing this, so I won't feel offended if you deny this PR, but I would like a similar solution and an upload to PyPI if possible because ChatExchange is currently unusable without a fix. (At least as far as I can tell.)
=> Fix user id retrieval bug

.gitignore, chatexchange/browser.py, chatexchange/client.py, tests/test_login.py, tests/test_messages.py, tests/test_openid_login.py, tests/test_rooms.py
`openid.stackexchange.com` is going away, as described in #151.  The old login flow was to first log into `openid.stackexchange.com`, and then use OpenID to authenticate to `stackoverflow.com` and `meta.stackexchange.com` as necessary.  With this PR, CE now logs in directly to SO (for chat.SO) and MSE (for chat.SE and chat.MSE) using email/password instead of OpenID.
---
While I was at it, I updated the test cases.  
- Some chat messages used as tests had been anonymized, so I made the transcript scraping more resilient wherever this caused exceptions.
- The test cases checked whether a certain user is a RO of the sandbox.  However, this user had been recently removed from the RO list.  I changed it to check for ProgramFOX instead, who is currently a sandbox RO.
- I added a test case for …
=> Remove deprecated OpenID login, fix tests

chatexchange/browser.py, chatexchange/client.py
Smokey has started to trigger captcha's on login. A lot. So... since the CE session gets lost across restarts, we need some way to restart it without logging in again - this is it.
=> Cookie-based login

chatexchange/browser.py, chatexchange/client.py
Adds some modifications that we've made to the Charcoal fork of ChatExchange. Thanks to @makyen for a number of these.
* Don't bother trying OpenID to log in since SE doesn't support it any more
* Improve sending efficiency by dropping extra waits since they don't appear to be necessary
* Add names for each thread
* BS4 update broke `get_current_users_in_room`: fix this
=> Updates from Charcoal

chatexchange/client.py
When it's necessary to wait for only 1 second, the response from SE Chat is:
> You can perform this action again in 1 second.
which doesn't match the current `TOO_FAST_RE` regular expression, because that regex requires "seconds" to be plural. This PR just changes the regular expression to not care if the response is singular or plural by removing the final `s`.
=> Recognize SE Chat response for 1 second wait

chatexchange/markdown_detector.py, chatexchange/rooms.py, tests/test_markdown.py
This is a follup-up to PR #155 which cleans up a couple of problems which I discovered after the PR was merged.
The 500-character message limit is *possible* to override with `length_check` but without it, we still force multi-line messages to remain below the 500 limit. This seems to be (approximately?) where Stack Exchange hides part of the message behind a **(see full text)** link so staying below it by default seems to make sense.
This introduces a much more disciplined attempt at identifying messages which are Markdown (because you can't merge lines when they have rich formatting). I tried to resist using regex but I failed. The result is fairly succinct and reasonably accurate under the circumstances, but it's probably still possible to find corner cases where it does the wrong …
=> Send aggressively fixup

.github/workflows/lint+test.yml, README.md, setup.py
Installing the package should not pull in complex development requirements by default
=> setup.py: move dev dependencies to extras_require

.github/workflows/lint+test.yml
Several of the Python platforms which used to work no longer exist for ubuntu-latest
Also, update actions to their latest versions (checkout@v3, setup-python@v4)
=> .github/workflows/lint+test.yml: update for ubuntu-latest

chatexchange/client.py
With this additional exception handler, the queue is properly drained when something fails, instead of retrying forever
(Closes: #164)
=> chatexchage/client.py: catch HTTPError for refused actions

docs/se-chat-interface.md
`se-chat-interface.md` file contains following string:
> All message events contain the the following fields based on the message they refer to:
I remove a type (double `the`)
> All message events contain the following fields based on the message they refer to:
=> Fix typo in se-chat-interface.md
