Manishearth/ChatExchange

- chatexchange/browser.py
- chatexchange/client.py
- chatexchange/rooms.py
Adds a `leave` method to `Room`.
> Add leave method to Room

- chatexchange/browser.py
- chatexchange/client.py
The commits in this PR fix the websocket recovery and add a default recovery method. See commit messages for more details.
> Fix websocket recovery + add default method

- chatexchange/events.py
The commits are a bit messy, hopefully it doesn't matter
> Add ability to see users who left or entered the room

- docs/Documentation.md
Creates documentation for the first file, `_utils.py`. I will be writing more documentation for the other files, but not right now because I'm tired.
> Documentation #01: _utils.py

- chatexchange/browser.py
- chatexchange/client.py
This broke after the new login rolled out... and turns out, we don't need it! I think this should work, but I'm not certain. Might want to make sure Travis passes and if not, revert this commit.
> Remove login_se_chat()

- chatexchange/browser.py
- chatexchange/rooms.py
As far as I found, the only way to do this is to parse some JavaScript that's in the page source of a chatroom.
> Add methods to get current users in room

- chatexchange/client.py
> Add an on_message_sent callback

- chatexchange/client.py
> Don't error on "ok" as response.

- chatexchange/client.py
> Raise after more than 5 attempts at unknown reason

- chatexchange/client.py
> Avoid obsolete way to create exception

- chatexchange/client.py
> Avoid ChatActionError when it's too late to delete/edit

- chatexchange/messages.py
> Add length_check parameter for reply

- chatexchange/client.py
r? @Manishearth 
It would probably be best to find some way to capture these errors, but since sending is async...
> Avoid ChatActionError when messages have been deleted

- chatexchange/_utils.py
- chatexchange/browser.py
and return it as a number of seconds since the user was seen.
> Scrape 'last seen' information from profiles

- chatexchange/browser.py
Can't say for sure if this works or not so I'll first let the Travis build run
> Fix UnicodeDecodeError for is_moderator

- chatexchange/browser.py
Attempt 2. I just looked up the pre-ChatExchange6 code for this.
> Fix error for is_moderator

- chatexchange/browser.py
- chatexchange/messages.py
Added star-cancelling functionality for ROs since it didn't seem to be implemented.
> Added star-cancelling functionality

- chatexchange/browser.py
Yes, apparently this *is* all that's needed.
> Make CE work with SE HTTPS

- chatexchange/browser.py
Jeremy Banks [updated some chat code](https://chat.stackoverflow.com/transcript/message/38538245#38538245), which breaks the way CE searches for message content on the history page. This *should* fix it; I'll keep looking for more occurrences but I think I've got it.
-----
okay that might work now
> Fix to match Jeremy's new chat code

- chatexchange/client.py
- chatexchange/rooms.py
rooms.py: sending functionality will merge a message with the previous message in the queue if possible if send_aggressively is set
client.py: PeekableQueue: extend queue.Queue with the ability to peek and poke the last added item
> client.py: send_aggressively=True to merge queued messages

- chatexchange/browser.py
SE changed the HTML/JS for chat rooms so the list of users present in the room is now provided as a JSON formatted list of complete user objects in a "data-users" attribute on a `<div class="js-present">`. Because one never knows when/if SE might revert their change, the scraping for the prior methodology is left as a fallback.
> get_current_users_in_room: Adapt to Stack Exchange HTML/JS changes

- chatexchange/client.py
Fallout from previous refactoring, sorry!
> client.py: define message_id = None even when unused

- chatexchange/client.py
Back out the complex refactoring and try to appease `flake8` with a less intrusive one.
> Refactoring redux

- README.md
Also, clean up formatting somewhat and remove old commentary
> README.md: No longer advertise this as Python 2 compatible

- chatexchange/browser.py
- chatexchange/client.py
> Fix DeprecationWarning on method `Thread.setDaemon`
